//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BlogPostEntities : DbContext
    {
        public BlogPostEntities()
            : base("name=BlogPostEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
