
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BOL
{

using System;
    using System.Collections.Generic;
    
public partial class Blog
{

    public int BlogId { get; set; }

    public string Title { get; set; }

    public string ImagePath { get; set; }

    public string Content { get; set; }

    public int StatusId { get; set; }

    public int userId { get; set; }



    public virtual Status Status { get; set; }

    public virtual tbl_user tbl_user { get; set; }

}

}
